### ISSUE TITLE
how can i access argv

### ISSUE THREAD

**Issue by Supersebi3** [eliaperantoni/Koi#1]
pls help how can i access argv (in python its sys.argv) in koi

**Comment by eliaperantoni** [comment]
Hello! There's currently no way to access argv but it's a pretty easy improvement.
How would you suggest that might be done? Would a string array declared globally and named `argv` do the trick?

**Comment by Supersebi3** [comment]
yeah, i think a global list called argv or ARGV should do the trick

**Comment by eliaperantoni** [comment]
Ok nice. Koi can take some arguments though. Would you suggest those are included like Python does:
```
$ python -c 'import sys; print(sys.argv)'
['-c']
```
or would a `---` to separate koi arguments from user arguments be better?

**Comment by Supersebi3** [comment]
when in doubt id probably go by what python does, but separating with --- also seems like a logical solution. ive only played with koi a little bit so far so i cant really decide what would be better

**Comment by Forbidden-A** [comment]
perhaps you can do it like `cargo run` does, where you can use `--` and its ignored.

$ cargo run -- test -a -b
>    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/a test -a -b`
target/debug/a
test
-a
-b

$ cargo run test -a -b
>    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/a test -a -b`
target/debug/a
test
-a
-b

ps. it just removes the first `--` it sees it seems.

$ cargo run -- -- a
>    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/a test -a -b`
target/debug/a
--
a

**Comment by subterfugue** [comment]
I suggest a different method that I really think would work here, personally:

You could either: 1. Just use Bash-like syntax for it e.g. (`$1`, `$2`) which is good for *some* kind of POSIX compliance, but I doubt you're going with that, and posix is mainly pretty ugly, IMO.

Now, 
2. I believe this option is the best, which is emulating what C, assembly, and etc do with argv, which is just the command ran seperated by spaces, e.g. if you run it with `koi script.koi` or something similar, argv would be a list being `["koi", "script.koi"]` (maybe also include `argc`?), I think this would be very expected behavior from people that use this, and would be pretty easy to handle, as most famous languages handle arguments as such. Thank you for making Koi, BTW :).

**Comment by eliaperantoni** [comment]
I really like what cargo does because I think arguments meant for Koi and arguments meant for the script should be clearly distinguishable.

What if a user makes a pretty complex script and wants to have an `--help` for it? Should that open Koi's help page or the script's?

It's way clearer with `--` (albeit more verbose) IMO:

```
$ koi myscript.koi --help
$ koi myscript.koi -- --help
```

**Comment by subterfugue** [comment]
Alright! I personally think that it's a very good idea, I'm all in for it!

**Comment by eliaperantoni** [comment]
[Added!](https://github.com/eliaperantoni/Koi/releases/tag/v1.6.0)

I figured calling it `args` instead of `argv` would be slightly better to avoid confusion since it's not exactly the same as `argv` in C and friends.

```
$ echo 'print(args)' > /tmp/argsdemo.koi && koi /tmp/argsdemo.koi -- --help -x 10 -y positional
['--help', '-x', '10', '-y', 'positional']
```

**Comment by Supersebi3** [comment]
another idea: what if options *before* the main file name count towards koi arguments and args *after* the main file name count towards the program? so

```
$ koi -f foo myscript.koi --config myconfig.json
```
would send `-f foo` to koi and `--config myconfig.json` to the script

this seems like a very logical and intuitive approach, but probably gets too complicated with other types of koi options. oh well, just wanted to give this input ig

**Comment by eliaperantoni** [comment]
This would require all flags to come before the script path right? Since the path is now effectively acting as a separator.

It's definitely a cool idea but I'm not entirely sure it's worth adding. One might be pretty confused that these two do different things:

```
$ koi myscript.koi --flag
$ koi --flag myscript.koi
```

**Comment by Supersebi3** [comment]
yeah, this is probably one of these cases where the initial idea seems great but in reality it ends up being too confusing. the current implementation you made seems fine :smile:

**Comment by Supersebi3** [comment]
welp, im sorry for bothering you continuously on this issue, but the current implementation is problematic when the script file is executed directly using a shebang line - lets say i have a file `test.koi` with the following content:

```
#!/bin/env koi

args.forEach(fn(a) {
    print(a)
})
```

i cant run this as 

```
$ ./test.koi foo bar baz
```

because that still gives the args to the koi command even though i dont explicitly run it. instead, i have to do 

```
./test.koi -- foo bar baz
```

to get the desired behavior. 

python seems to handle a situation like this quite well, so once again maybe using pythons approach to arg parsing would make sense here

**Comment by eliaperantoni** [comment]
No problem, I'm really flattered that Koi is getting some attention and appreciate the time you put in to report these issues 😊.

I would have said that was kinda the expected behaviour actually.

Maybe exposing `argv` directly as you're suggesting is the best idea. The user could still apply the cargo-style pattern (if he wanted to) by simply ignoring everything that comes before the string `--` in the `argv` vector.

**Comment by eliaperantoni** [comment]
Thinking about it some more: I think `args` is kinda fine as-is. It may come with some quirks (especially using the shebang as you've highlighted) but I like its simplicity (simply splitting on the first `--`) which provides an easy way to ignore all flags and options specific to the Koi's interpreter.
Maybe a global `argv` (as opposed to `args`) could be exposed in the future as a more obscure feature for advanced users with edge cases (Python too "hides" it under the `sys` module).
