### ISSUE TITLE
Return code from running external command?

### ISSUE THREAD

**Issue by manfredlotz** [eliaperantoni/Koi#12]
When running a command in a shell script then `$?` gives the return code of that command.

I did not find how I get the return code in a koi script.

**Comment by eliaperantoni** [comment]
Greetings! This wasn't possible but it is now starting with the 1.7.0 release:
https://github.com/eliaperantoni/Koi/releases/tag/v1.7.0
The return code can be read using the `rc` global variable.

Here's a toy example:
```
python -c "exit(36)"
print(rc)
```

**Comment by manfredlotz** [comment]
Looks good. Thank you.

You only forgot to update 1.0.0 in `main.rc`.

**Comment by eliaperantoni** [comment]
That's absolutely right, will do asap!

**Comment by balupton** [comment]
One thing to note, the correct terminology when it comes to the shell command invocation is `exit status` rather than `return code`.

For those interested in common ones, I put together this piece of documentation: https://github.com/bevry/dorothy/blob/master/docs/bash/errors.md#errors

I'm also guessing that in Koi non-zero exit statuses of external commands do not throw exceptions?
