### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by eode** [eliaperantoni/Koi#14]
Traceback in `main.rs:65:9` -- "called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }"

**Comment by kseistrup** [comment]
That unhelpful error also puzzled me until I investigated what files `köi` attempts to open upon startup.

If you `touch Koifile` in the current directory, `köi` will not crash.

It still feels like a bug, though.

Edit: typo

**Comment by eliaperantoni** [comment]
@eode @kseistrup Sorry for the delay. Indeed Koi needs to read a source file. The path is `./Koifile`, unless an argument is provided (e.g. `koi path_to_file`). So the error you see is due to the fact that you haven't provided a path to a source file, and there's no `Koifile`. I've pushed a commit that should hopefully improve the error message.
